#pragma once

enum ConsoleColor
{
	CONSOLE_FORE_COLOR_BLACK = 0,
	CONSOLE_FORE_COLOR_BLUE = 1,
	CONSOLE_FORE_COLOR_GREEN = 2,
	CONSOLE_FORE_COLOR_CYAN = 3,
	CONSOLE_FORE_COLOR_RED = 4,
	CONSOLE_FORE_COLOR_MAGENTA = 5,
	CONSOLE_FORE_COLOR_BROWN = 6,
	CONSOLE_FORE_COLOR_LIGHTGRAY = 7,
	CONSOLE_FORE_COLOR_DARKGRAY = 8,
	CONSOLE_FORE_COLOR_LIGHTBLUE = 9,
	CONSOLE_FORE_COLOR_LIGHTGREEN = 10,
	CONSOLE_FORE_COLOR_LIGHTCYAN = 11,
	CONSOLE_FORE_COLOR_LIGHTRED = 12,
	CONSOLE_FORE_COLOR_LIGHTMAGENTA = 13,
	CONSOLE_FORE_COLOR_YELLOW = 14,
	CONSOLE_FORE_COLOR_WHITE = 15
};

enum MSG_TYPE
{
	MSG_NORMAL
};

class ShowMessageSystem
{
public:

	ShowMessageSystem();
	static void ShowMessage(bool nStatus, MSG_TYPE type, ConsoleColor sColor, LPCSTR msg, ...);
	static void color_c(char* buff, WORD color);
};